[tools]
# =================================================================================================
# Project Tools
# =================================================================================================
go = "1.26.0"
"aqua:golangci/golangci-lint" = "2.8.0"
"aqua:goreleaser/goreleaser" = "2.13.3"


# =================================================================================================
# CI Tools
# =================================================================================================
"aqua:rhysd/actionlint" = "1"
svu = "latest"
