[tools]
# =================================================================================================
# Project Tools
# =================================================================================================
go = "1.25.4"
"aqua:golangci/golangci-lint" = "2.6.2"
"aqua:goreleaser/goreleaser" = "2.12.7"


# =================================================================================================
# CI Tools
# =================================================================================================
"aqua:rhysd/actionlint" = "1"
"npm:@commitlint/cli" = "20"
